# nnimage.conf - test configuration file

image test
{
    size: 512MiB;
    bootmode: bios;
    type: mbr;
    partitions: test1;
}

partition test1
{
    size: 128MiB;
    start: 1MiB;
    format: fat32;
    test: "test \"";
}
