# nnimage.conf - test configuration file

image test
{
    size: 1440KiB;
    bootmode: bios;
    type: floppy;
    partitions: test1, test2, test3;
}

partition test1
{
    format: "fat12";
    isboot: true;
}
