# nnimage.conf - test configuration file

image test
{
    size: 1440KiB;
    boot_mode: bios;
    type: floppy;
    partitions: test1, test2, test3;
}

partition test1
{
    fs_type: fat12;
    is_boot: true;
}
