/*
    TestDriver.cxx - Test driver for nnimage
    Copyright 2026 Jedidiah Thompson

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

#define DOCTEST_CONFIG_IMPLEMENT

#include "include/Log.h"
#include "doctest.h"

// NOTE: This test driver is only compiled if NNIMAGE_ENABLE_TESTS is enabled at configure time

// NOTE2: most of these test cases have been generated by AI for the time being.
// I need to go through here and clean them up and ensure everything is correct, but that is a
// future task. For now, these tests are just to ensure that the system is working and that the
// basic functionality is correct.

// Main test driver function that sets up the doctest context and runs the tests
bool TestDriver (int argc, char** argv)
{
    _log->SetLogLevel (LogLevel::Fatal);

    doctest::Context ctx;
    ctx.applyCommandLine (argc, argv);
    int res = ctx.run();
    return !res;
}
