#!/bin/sh
# generate_components.sh - Generate component enum/name/factory tables for nnimage
# Copyright 2026 Jedidiah Thompson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

panic()
{
    echo "$0: error: $1"
    exit 1
}

# Makes an enum value name from a component name, e.g. "mbr" -> "Mbr"
makecompvar()
{
    echo "$1" | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}'
}

# Gets variable from comp file
getcompvar()
{
    eval "$2="
    . "$1"
    eval "printf '%s\\n' \"\${$2}\""
}

compsdir=$1
outdir=$2

[ -z "$compsdir" ] && panic "Component source directory not specified"
[ -z "$outdir" ] && panic "Output directory not specified"

typesfile="$4"
tablefile="$3"
compsfile="$5"

[ -z "$typesfile" ] && panic "Types file not specified"
[ -z "$tablefile" ] && panic "Table file not specified"
[ -z "$compsfile" ] && panic "Comps file not specified"

echo "/* This file is auto-generated by generate_components.sh. Do not edit manually. */" > "$typesfile"
echo "#ifndef COMPTYPES_H" >> "$typesfile"
echo "#define COMPTYPES_H" >> "$typesfile"

echo "/* This file is auto-generated by generate_components.sh. Do not edit manually. */" > "$tablefile"
echo "#ifndef COMPTABLE_H" >> "$tablefile"
echo "#define COMPTABLE_H" >> "$tablefile"
echo "" >> "$tablefile"
echo "#include \"include/ImgComponent.h\"" >> "$tablefile"
echo "#include \"Components.h\"" >> "$tablefile"
echo "" >> "$tablefile"
echo "#include <functional>" >> "$tablefile"
echo "#include <memory>" >> "$tablefile"
echo "" >> "$tablefile"

echo "/* This file is auto-generated by generate_components.sh. Do not edit manually. */" > "$compsfile"


slotfiles=$(ls "$compsdir"/slots/*.comp | tr '\n' ' ')
slots=

for curslot in $slotfiles
do
    slots="${slots} $(basename ${curslot%.comp})"
done

for slot in $slots
do
    # Get the slots desc file
    sf="$compsdir/slots/$slot.comp"
    enumname=$(getcompvar "$sf" "ENUMNAME")
    [ -z "$enumname" ] && panic "Slot file missing ENUMNAME"
    baseclass=$(getcompvar "$sf" "BASECLASS")
    [ -z "$baseclass" ] && panic "Slot file missing BASECLASS"
    nameregistry=$(getcompvar "$sf" "NAMEREGISTRY")
    [ -z "$nameregistry" ] && panic "Slot file missing NAMEREGISTRY"
    factoryregistry=$(getcompvar "$sf" "FACTORYREGISTRY")
    [ -z "$factoryregistry" ] && panic "Slot file missing FACTORYREGISTRY"

    nameregistry="$baseclass::$nameregistry"
    factoryregistry="$baseclass::$factoryregistry"

    mkdir -p "$outdir"

    # Find every .comp file belonging to this slot
    matchedfiles=""
    for f in "$compsdir"/decl/*.comp
    do
        [ -e "$f" ] || continue
        fileslot=$(getcompvar "$f" "SLOT")
        [ "$fileslot" = "$slot" ] && matchedfiles="$matchedfiles $f"
    done

    [ -z "$matchedfiles" ] && panic "No .comp files found for slot \"$slot\" in \"$compsdir\""

    lastfile=$(echo "$matchedfiles" | awk '{print $NF}')

    #########################
    # GENERATION BEGINS HERE
    #########################

    # Types header: fixed enum of every variant for this slot, plus each variant's own header
    echo "" >> "$typesfile"
    echo "enum class $enumname {" >> "$typesfile"
    for f in $matchedfiles
    do
        name=$(getcompvar "$f" "NAME")
        [ -z "$name" ] && panic "Component file \"$f\" is missing NAME"
        echo "    $(makecompvar "$name")," >> "$typesfile"
    done
    echo "    Max" >> "$typesfile"
    echo "};" >> "$typesfile"
    echo "" >> "$typesfile"

    includedheaders=""
    for f in $matchedfiles
    do
        header=$(getcompvar "$f" "HEADER")
        [ -z "$header" ] && panic "Component file \"$f\" is missing HEADER"
        case " $includedheaders " in
            *" $header "*) continue ;;
        esac
        includedheaders="$includedheaders $header"
        echo "#include \"$header\"" >> "$compsfile"
    done
    echo "" >> "$compsfile"

    # Table file: name -> enum map, and enum -> factory lambda table
    echo "" >> "$tablefile"

    echo "const NameRegistry<$enumname> $nameregistry = {" >> "$tablefile"
    for f in $matchedfiles
    do
        name=$(getcompvar "$f" "NAME")
        printf "    {\"%s\", %s::%s}" "$name" "$enumname" "$(makecompvar "$name")" >> "$tablefile"
        [ "$f" != "$lastfile" ] && echo "," >> "$tablefile" || echo "" >> "$tablefile"
    done
    echo "};" >> "$tablefile"
    echo "" >> "$tablefile"

    echo "class Image;" >> "$tablefile"
    echo "" >> "$tablefile"

    echo "const EnumArray<$enumname, std::function<std::unique_ptr<PartTypeComp>(Image&)>, ${enumname}::Max> $factoryregistry = {" >> "$tablefile"
    for f in $matchedfiles
    do
        class=$(getcompvar "$f" "CLASS")
        [ -z "$class" ] && panic "Component file \"$f\" is missing CLASS"
        printf "    [] (Image& img) { return std::make_unique<%s> (img); }" "$class" >> "$tablefile"
        [ "$f" != "$lastfile" ] && echo "," >> "$tablefile" || echo "" >> "$tablefile"
    done
    echo "};" >> "$tablefile"
    echo "" >> "$tablefile"
done

echo "#endif" >> "$tablefile"
echo "#endif" >> "$typesfile"
