#!/usr/bin/env python3
# generate_components.py - Generate component enum/name/factory tables for nnimage
# Copyright 2026 Jedidiah Thompson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: this file was AI-generated as I'm not familiar with python and was feeling lazy that day
# I should have hand written it in retrospec but it should be fine

import argparse
from pathlib import Path

COMMENTHEADER = "/* This file is auto-generated by generate_components.py. Do not edit manually. */"


def componentTypeName(name: str) -> str:
    return name[:1].upper() + name[1:]


def readComponentFile(path: Path) -> dict[str, str]:
    values = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, value = line.partition("=")
        if separator:
            values[name] = value
    return values


def requiredValue(values: dict[str, str], name: str, path: Path) -> str:
    value = values.get(name, "")
    if not value:
        raise ValueError(f'Component file "{path}" is missing {name}')
    return value


def outputTypes(slots: list[tuple[dict[str, str], list[dict[str, str]]]]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef COMPTYPES_H",
        "#define COMPTYPES_H",
    ]

    for descriptor, components in slots:
        lines.extend(["", f"enum class {descriptor['ENUMNAME']} {{"])
        for component in components:
            lines.append(f"    {componentTypeName(component['NAME'])},")
        lines.extend(["    Max", "};"])

    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def outputTable(slots: list[tuple[dict[str, str], list[dict[str, str]]]]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef COMPTABLE_H",
        "#define COMPTABLE_H",
        "",
        '#include "include/image/ImgComponent.h"',
        '#include "Components.h"',
        "",
        "#include <functional>",
        "#include <memory>",
        "",
        "class Image;",
    ]

    for descriptor, components in slots:
        enumname = descriptor["ENUMNAME"]
        baseclass = descriptor["BASECLASS"]
        nameregistry = f"{baseclass}::{descriptor['NAMEREGISTRY']}"
        factoryregistry = f"{baseclass}::{descriptor['FACTORYREGISTRY']}"

        lines.extend(["", f"const NameRegistry<{enumname}> {nameregistry} = {{"])
        for index, component in enumerate(components):
            comma = "," if index < len(components) - 1 else ""
            lines.append(
                f'    {{"{component["NAME"]}", {enumname}::{componentTypeName(component["NAME"] )}}}{comma}'
            )
        lines.extend(["};", ""])

        lines.append(
            f"const EnumArray<{enumname}, std::function<std::unique_ptr<{baseclass}>(Image&)>, "
            f"{enumname}::Max> {factoryregistry} = {{"
        )
        for index, component in enumerate(components):
            comma = "," if index < len(components) - 1 else ""
            lines.append(
                f"    [] (Image& img) {{ return std::make_unique<{component['CLASS']}> (img); }}{comma}"
            )
        lines.extend(["};", ""])

    lines.extend(["#endif", ""])
    return "\n".join(lines)


def outputInclude(slots: list[tuple[dict[str, str], list[dict[str, str]]]]) -> str:
    lines = [COMMENTHEADER]
    includedHeaders = []
    for _, components in slots:
        for component in components:
            header = component["HEADER"]
            if header not in includedHeaders:
                includedHeaders.append(header)
                lines.append(f'#include "{header}"')

    lines.append("")
    return "\n".join(lines)


def readSlots(compsDir: Path) -> list[tuple[dict[str, str], list[dict[str, str]]]]:
    slots = []
    for descriptorPath in sorted((compsDir / "slots").glob("*.comp")):
        descriptor = readComponentFile(descriptorPath)
        for name in ("ENUMNAME", "BASECLASS", "NAMEREGISTRY", "FACTORYREGISTRY"):
            requiredValue(descriptor, name, descriptorPath)

        slot = descriptorPath.stem
        slotDir = compsDir / "slots" / slot
        componentPaths = sorted(slotDir.glob("*.comp"))
        if not componentPaths:
            raise ValueError(f'No .comp files found for slot "{slot}" in "{slotDir}"')

        components = []
        for componentPath in componentPaths:
            component = readComponentFile(componentPath)
            for name in ("NAME", "SLOT", "CLASS", "HEADER"):
                requiredValue(component, name, componentPath)
            if component["SLOT"] == slot:
                components.append(component)

        if not components:
            raise ValueError(f'No .comp files found for slot "{slot}" in "{slotDir}"')
        slots.append((descriptor, components))
    return slots


parser = argparse.ArgumentParser()
parser.add_argument("compsDir", type=Path)
parser.add_argument("buildDir", type=Path)
args = parser.parse_args()

try:
    slots = readSlots(args.compsDir)
except ValueError as error:
    parser.error(str(error))

args.buildDir.mkdir(parents=True, exist_ok=True)
(args.buildDir / "CompTypes.h").write_text(outputTypes(slots), encoding="utf-8")
(args.buildDir / "CompTable.h").write_text(outputTable(slots), encoding="utf-8")
(args.buildDir / "Components.h").write_text(outputInclude(slots), encoding="utf-8")
