#!/usr/bin/env python3
# generate_backends.py - contains script to generate backends header
# Copyright 2026 Jedidiah Thompson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
from pathlib import Path

# Standard code things
COMMENTHEADER = "/* This file is auto-generated by generate_backends.py. Do not edit manually. */"

def backendTypeName (name: str) -> str:
    return name[:1].upper() + name[1:]

def parseBackends (value: str) -> list[str]:
    backends = value.split (",")
    if not backends:
        raise argparse.ArgumentTypeError ("backend list can't be empty")
    return backends

def outputTypes (backends: list[str]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef BACKENDTYPES_H",
        "#define BACKENDTYPES_H",
        "",
        "#include \"include/EnumArray.h\"",
        "",
        "enum class BackendType",
        "{",
        "    None,"
    ]
    for backend in backends:
        lines.append (f"    {backendTypeName(backend)},")

    lines.extend ([
        "    Max",
        "};",
        "",
        "#endif",
        ""
    ])
    return "\n".join (lines)

def outputTable (backends: list[str], enabledBackends: list[str]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef BACKENDTABLE_H",
        "#define BACKENDTABLE_H",
        "",
        "#include \"BackendTypes.h\"",
        "#include \"Backends.h\"",
        "",
        "#include <functional>",
        "#include <memory>",
        "#include <string>",
        "#include <unordered_map>",
        "",
        "static const std::unordered_map<std::string, BackendType> BackendNameRegistry = {"
    ]

    for backend in enabledBackends:
        lines.append (f'    {{"{backend}", BackendType::{backendTypeName(backend)}}},')
    lines.extend ([
        "};",
        "",
        "static EnumArray<BackendType, std::function<std::unique_ptr<Backend>()>, BackendType::Max> BackendFactoryRegistry = {"
        "    nullptr,"
    ])

    for backend in backends:
        if backend in enabledBackends:
            lines.append (f"    []() {{ return std::make_unique<{backendTypeName(backend)}Backend>(); }},")
        else:
            lines.append("    nullptr,")

    lines.extend ([
        "};",
        "",
        "#endif",
        ""
    ])
    return "\n".join (lines)

def outputInclude (enabledBackends: list[str]) -> str:
    lines = [
        COMMENTHEADER,
        ""
    ]

    for backend in enabledBackends:
        lines.append (f'#include "backend/{backendTypeName(backend)}Backend.h"')

    lines.append ("")
    return "\n".join (lines)

parser = argparse.ArgumentParser();
parser.add_argument ("enabledBackends", type=parseBackends)
parser.add_argument ("allBackends", type=parseBackends)
parser.add_argument ("buildDir", type=Path)

args = parser.parse_args()

typesHeader = args.buildDir / "BackendTypes.h"
tableHeader = args.buildDir / "BackendTable.h"
backendHeader = args.buildDir / "Backends.h"

typesHeader.write_text (
    outputTypes (args.allBackends),
    encoding="utf-8"
)

tableHeader.write_text (
    outputTable (args.allBackends, args.enabledBackends),
    encoding="utf-8"
)

backendHeader.write_text (
    outputInclude (args.enabledBackends),
    encoding="utf-8"
)
