#!/bin/sh
# generate_backends.sh - Generate BackendTypes.h for nnimage
# Copyright 2026 Jedidiah Thompson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

panic()
{
    echo "$0: error: $1"
    exit 1
}

# Makes variable name from a backend name, e.g. "krun" -> "Krun"
makebackendvar()
{
    echo "$1" | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}'
}

enabledbackends=$1
allbackends=$2
typesfile=$4
tablefile=$3

[ -z "$enabledbackends" ] && panic "Enabled backends not specified"
[ -z "$tablefile" ] && panic "Table file not specified"
[ -z "$typesfile" ] && panic "Types file not specified"
[ -z "$allbackends" ] && panic "All backends not specified"

# Ensure enabled backends becomes space seperated
enabledbackends=$(echo "$enabledbackends" | tr ',' ' ')
allbackends=$(echo "$allbackends" | tr ',' ' ')
# Store last backend in a variable so we can use it to avoid trailing commas in the generated code
lastbackend=$(echo "$enabledbackends" | awk '{print $NF}')
lastallbackend=$(echo "$allbackends" | awk '{print $NF}')

#########################
# GENERATION BEGINS HERE
#########################

# Start by generating the backend types header file
outputfile="$typesfile"

echo "/* This file is auto-generated by generate_backends.sh. Do not edit manually. */" > "$outputfile"
echo "#ifndef BACKENDTYPES_H" >> "$outputfile"
echo "#define BACKENDTYPES_H" >> "$outputfile"
echo "" >> "$outputfile"
echo "#include \"include/EnumArray.h\"" >> "$outputfile"
echo "" >> "$outputfile"

# Generate enum for all backends
# We do this because we want to have a fixed enum for all backends, even if some are not enabled
# This allows us to effectively communicate to the user wheter a backend is enabled,
# and also some code is dependent on the enum values being fixed
echo "enum class BackendType {" >> "$outputfile"
echo "    None," >> "$outputfile"
for backend in $allbackends
do
    backendvar=$(makebackendvar "$backend")
    echo "    $backendvar," >> "$outputfile"
done
# Add max field
echo "    Max" >> "$outputfile"
echo "};" >> "$outputfile"
echo "" >> "$outputfile"

# Add include for each backend
for backend in $enabledbackends
do
    backendvar=$(makebackendvar "$backend")
    echo "#include \"backend/${backendvar}Backend.h\"" >> "$outputfile"
done
echo "" >> "$outputfile"
echo "#endif" >> "$outputfile"

# Now generate the table file
outputfile="$tablefile"
echo "/* This file is auto-generated by generate_backends.sh. Do not edit manually. */" > "$outputfile"
echo "#ifndef BACKENDTABLE_H" >> "$outputfile"
echo "#define BACKENDTABLE_H" >> "$outputfile"
echo "" >> "$outputfile"
echo "#include \"BackendTypes.h\"" >> "$outputfile"
echo "#include <unordered_map>" >> "$outputfile"

# Generate name array for enabled backends
echo "" >> "$outputfile"
echo "static const std::unordered_map<std::string, BackendType> BackendNameRegistry = {" >> "$outputfile"
for backend in $enabledbackends
do
    backendvar=$(makebackendvar "$backend")
    printf "    {\"$backend\", BackendType::$backendvar}" >> "$outputfile"
    [ "$backend" != "$lastbackend" ] && echo "," >> "$outputfile" || echo "" >> "$outputfile"
done
echo "};" >> "$outputfile"
echo "" >> "$outputfile"

# Lastly, generate table of lambdas to create backend instances
echo "static EnumArray<BackendType, std::function<std::unique_ptr<Backend>()>> BackendFactoryRegistry = {" >> "$outputfile"
echo "    nullptr," >> "$outputfile"
for backend in $allbackends
do
    backendvar=$(makebackendvar "$backend")
    if echo " $enabledbackends " | grep -q " $backend "
    then
        printf "    []() { return std::make_unique<${backendvar}Backend>(); }" >> "$outputfile"
    else
        printf "    nullptr" >> "$outputfile"
    fi
    [ "$backend" != "$lastallbackend" ] && echo "," >> "$outputfile" || echo "" >> "$outputfile"
done
echo "};" >> "$outputfile"
echo "" >> "$outputfile"

echo "#endif" >> "$outputfile"
