#!/usr/bin/env python3
# generate_components.py - Generate component enum/name/factory tables for nnimage
# Copyright 2026 Jedidiah Thompson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: this file was AI-generated as I'm not familiar with python and was feeling lazy that day
# I should have hand written it in retrospec but it should be fine

import argparse
from pathlib import Path
from dataclasses import dataclass

COMMENTHEADER = "/* This file is auto-generated by generate_components.py. Do not edit manually. */"

# A struct representing a component
@dataclass
class Component:
    vals: dict[str, str]

# A struct representing a slot
@dataclass
class Slot:
    vals: dict[str, str]
    components: list[Component]

def componentTypeName(name: str) -> str:
    return name[:1].upper() + name[1:]


def readComponentFile(path: Path) -> dict[str, str]:
    values = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name, separator, value = line.partition("=")
        if not separator:
            raise ValueError(f'Component file "{path}" is missing a seperator')
        values[name] = value
    return values


def requiredValue(values: dict[str, str], name: str, path: Path) -> str:
    value = values.get(name, "")
    if not value:
        raise ValueError(f'Component file "{path}" is missing {name}')
    return value


def outputTypes(slots: list[Slot]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef COMPTYPES_H",
        "#define COMPTYPES_H",
    ]

    for slot in slots:
        lines.extend(["", f"enum class {slot.vals['ENUMNAME']} {{"])
        for component in slot.components:
            lines.append(f"    {componentTypeName(component.vals['NAME'])},")
        lines.extend(["    Max", "};"])

    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def outputCompType(slots: list[Slot]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef COMPTYPE_H",
        "#define COMPTYPE_H",
        "",
        "enum class CompType",
        "{",
    ]

    for slot in slots:
        lines.append(f"    {slot.vals['COMPTYPE']},")
    lines.append("    Max")

    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def outputTable(slots: list[Slot]) -> str:
    lines = [
        COMMENTHEADER,
        "#ifndef COMPTABLE_H",
        "#define COMPTABLE_H",
        "",
        '#include "include/image/ImgComponent.h"',
        '#include "Components.h"',
        "",
        "#include <functional>",
        "#include <memory>",
        "",
        "class Image;",
    ]

    for slot in slots:
        enumname = slot.vals["ENUMNAME"]
        baseclass = slot.vals["BASECLASS"]
        nameregistry = f"{baseclass}::{slot.vals['NAMEREGISTRY']}"
        factoryregistry = f"{baseclass}::{slot.vals['FACTORYREGISTRY']}"

        lines.extend(["", f"const NameRegistry<{enumname}> {nameregistry} = {{"])
        for index, component in enumerate(slot.components):
            comma = "," if index < len(slot.components) - 1 else ""
            lines.append(
                f'    {{"{component.vals["NAME"]}", {enumname}::{componentTypeName(component.vals["NAME"] )}}}{comma}'
            )
        lines.extend(["};", ""])

        lines.append(
            f"const EnumArray<{enumname}, std::function<std::unique_ptr<{baseclass}>(Image&)>, "
            f"{enumname}::Max> {factoryregistry} = {{"
        )
        for index, component in enumerate(slot.components):
            comma = "," if index < len(slot.components) - 1 else ""
            lines.append(
                f"    [] (Image& img) {{ return std::make_unique<{component.vals['CLASS']}> (img); }}{comma}"
            )
        lines.extend(["};", ""])

        lines.extend([
            f"std::unique_ptr<{baseclass}> {baseclass}::Factory ({enumname} type, Image& owner)",
            "{",
            f"    return {slot.vals['FACTORYREGISTRY']}[type](owner);",
            "}",
            "",
            f"std::unique_ptr<{baseclass}> {baseclass}::Factory (std::string_view type, Image& owner)",
            "{",
            f"    {enumname} typeVal = {slot.vals['NAMEREGISTRY']}.Resolve (type);",
            f"    if (typeVal == {enumname}::Max)",
            "        return nullptr;",
            f"    return {slot.vals['FACTORYREGISTRY']}[typeVal](owner);",
            "}",
            "",
        ])

    lines.extend(["#endif", ""])
    return "\n".join(lines)


def outputInclude(slots: list[Slot]) -> str:
    lines = [COMMENTHEADER]
    includedHeaders = []
    for slot in slots:
        for component in slot.components:
            header = component.vals["HEADER"]
            if header not in includedHeaders:
                includedHeaders.append(header)
                lines.append(f'#include "{header}"')

    lines.append("")
    return "\n".join(lines)

SLOTPROPS = ["ENUMNAME", "BASECLASS", "NAMEREGISTRY", "FACTORYREGISTRY", "COMPTYPE"]
COMPPROPS = ["NAME", "SLOT", "CLASS", "HEADER"]

def readSlots(compsDir: Path) -> list[Slot]:
    slotList = []
    # Start by reading all .comp files in the slot directory
    slots = sorted((compsDir / "slots").glob("*.comp"))
    for slot in slots:
        vals = readComponentFile(slot)
        slotObj = Slot({}, [])
        # Check all the properties
        for prop in SLOTPROPS:
            requiredValue(vals, prop, slot)
            slotObj.vals[prop] = vals[prop]
        # Now get the components
        slotDir = compsDir / "slots" / slot.stem
        comps = slotDir.glob("*.comp")

        if not comps:
            raise ValueError(f"No found component files for slot {slot.stem}")
        for comp in comps:
            compVals = readComponentFile(comp)
            compObj = Component({})

            for prop in COMPPROPS:
                requiredValue(compVals, prop, comp)
                compObj.vals[prop] = compVals[prop]
                if prop == "SLOT":
                    slotObj.components.append(compObj)
        slotList.append(slotObj)
    return slotList

parser = argparse.ArgumentParser()
parser.add_argument("compsDir", type=Path)
parser.add_argument("buildDir", type=Path)
args = parser.parse_args()

try:
    slots = readSlots(args.compsDir)
except ValueError as error:
    parser.error(str(error))

(args.buildDir / "CompTypes.h").write_text(outputTypes(slots), encoding="utf-8")
(args.buildDir / "CompTable.h").write_text(outputTable(slots), encoding="utf-8")
(args.buildDir / "Components.h").write_text(outputInclude(slots), encoding="utf-8")

(args.buildDir / "include").mkdir(parents=True, exist_ok=True)
(args.buildDir / "include" / "CompType.h").write_text(outputCompType(slots), encoding="utf-8")
